// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: src/grpc/proto/arbitrage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "arbitrage";

export interface ArbsOnChainRequest {
  chainId: number;
}

export interface OnChainArbitragePathUnit {
  tokenInAddress: string;
  tokenOutAddress: string;
  poolAddress: string;
  amountIn: string;
  amountOut: string;
}

export interface OnChainArbitrage {
  path: OnChainArbitragePathUnit[];
}

export interface ArbsOnChainResponse {
  chainId: number;
  arbitrages: OnChainArbitrage[];
}

function createBaseArbsOnChainRequest(): ArbsOnChainRequest {
  return { chainId: 0 };
}

export const ArbsOnChainRequest: MessageFns<ArbsOnChainRequest> = {
  encode(message: ArbsOnChainRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainId !== 0) {
      writer.uint32(8).int64(message.chainId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArbsOnChainRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArbsOnChainRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.chainId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArbsOnChainRequest {
    return { chainId: isSet(object.chainId) ? globalThis.Number(object.chainId) : 0 };
  },

  toJSON(message: ArbsOnChainRequest): unknown {
    const obj: any = {};
    if (message.chainId !== 0) {
      obj.chainId = Math.round(message.chainId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArbsOnChainRequest>, I>>(base?: I): ArbsOnChainRequest {
    return ArbsOnChainRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArbsOnChainRequest>, I>>(object: I): ArbsOnChainRequest {
    const message = createBaseArbsOnChainRequest();
    message.chainId = object.chainId ?? 0;
    return message;
  },
};

function createBaseOnChainArbitragePathUnit(): OnChainArbitragePathUnit {
  return { tokenInAddress: "", tokenOutAddress: "", poolAddress: "", amountIn: "", amountOut: "" };
}

export const OnChainArbitragePathUnit: MessageFns<OnChainArbitragePathUnit> = {
  encode(message: OnChainArbitragePathUnit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tokenInAddress !== "") {
      writer.uint32(10).string(message.tokenInAddress);
    }
    if (message.tokenOutAddress !== "") {
      writer.uint32(18).string(message.tokenOutAddress);
    }
    if (message.poolAddress !== "") {
      writer.uint32(26).string(message.poolAddress);
    }
    if (message.amountIn !== "") {
      writer.uint32(34).string(message.amountIn);
    }
    if (message.amountOut !== "") {
      writer.uint32(42).string(message.amountOut);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OnChainArbitragePathUnit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOnChainArbitragePathUnit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tokenInAddress = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenOutAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.poolAddress = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amountIn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.amountOut = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OnChainArbitragePathUnit {
    return {
      tokenInAddress: isSet(object.tokenInAddress) ? globalThis.String(object.tokenInAddress) : "",
      tokenOutAddress: isSet(object.tokenOutAddress) ? globalThis.String(object.tokenOutAddress) : "",
      poolAddress: isSet(object.poolAddress) ? globalThis.String(object.poolAddress) : "",
      amountIn: isSet(object.amountIn) ? globalThis.String(object.amountIn) : "",
      amountOut: isSet(object.amountOut) ? globalThis.String(object.amountOut) : "",
    };
  },

  toJSON(message: OnChainArbitragePathUnit): unknown {
    const obj: any = {};
    if (message.tokenInAddress !== "") {
      obj.tokenInAddress = message.tokenInAddress;
    }
    if (message.tokenOutAddress !== "") {
      obj.tokenOutAddress = message.tokenOutAddress;
    }
    if (message.poolAddress !== "") {
      obj.poolAddress = message.poolAddress;
    }
    if (message.amountIn !== "") {
      obj.amountIn = message.amountIn;
    }
    if (message.amountOut !== "") {
      obj.amountOut = message.amountOut;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OnChainArbitragePathUnit>, I>>(base?: I): OnChainArbitragePathUnit {
    return OnChainArbitragePathUnit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OnChainArbitragePathUnit>, I>>(object: I): OnChainArbitragePathUnit {
    const message = createBaseOnChainArbitragePathUnit();
    message.tokenInAddress = object.tokenInAddress ?? "";
    message.tokenOutAddress = object.tokenOutAddress ?? "";
    message.poolAddress = object.poolAddress ?? "";
    message.amountIn = object.amountIn ?? "";
    message.amountOut = object.amountOut ?? "";
    return message;
  },
};

function createBaseOnChainArbitrage(): OnChainArbitrage {
  return { path: [] };
}

export const OnChainArbitrage: MessageFns<OnChainArbitrage> = {
  encode(message: OnChainArbitrage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.path) {
      OnChainArbitragePathUnit.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OnChainArbitrage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOnChainArbitrage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path.push(OnChainArbitragePathUnit.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OnChainArbitrage {
    return {
      path: globalThis.Array.isArray(object?.path)
        ? object.path.map((e: any) => OnChainArbitragePathUnit.fromJSON(e))
        : [],
    };
  },

  toJSON(message: OnChainArbitrage): unknown {
    const obj: any = {};
    if (message.path?.length) {
      obj.path = message.path.map((e) => OnChainArbitragePathUnit.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OnChainArbitrage>, I>>(base?: I): OnChainArbitrage {
    return OnChainArbitrage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OnChainArbitrage>, I>>(object: I): OnChainArbitrage {
    const message = createBaseOnChainArbitrage();
    message.path = object.path?.map((e) => OnChainArbitragePathUnit.fromPartial(e)) || [];
    return message;
  },
};

function createBaseArbsOnChainResponse(): ArbsOnChainResponse {
  return { chainId: 0, arbitrages: [] };
}

export const ArbsOnChainResponse: MessageFns<ArbsOnChainResponse> = {
  encode(message: ArbsOnChainResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainId !== 0) {
      writer.uint32(8).int64(message.chainId);
    }
    for (const v of message.arbitrages) {
      OnChainArbitrage.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArbsOnChainResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArbsOnChainResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.chainId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.arbitrages.push(OnChainArbitrage.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArbsOnChainResponse {
    return {
      chainId: isSet(object.chainId) ? globalThis.Number(object.chainId) : 0,
      arbitrages: globalThis.Array.isArray(object?.arbitrages)
        ? object.arbitrages.map((e: any) => OnChainArbitrage.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ArbsOnChainResponse): unknown {
    const obj: any = {};
    if (message.chainId !== 0) {
      obj.chainId = Math.round(message.chainId);
    }
    if (message.arbitrages?.length) {
      obj.arbitrages = message.arbitrages.map((e) => OnChainArbitrage.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArbsOnChainResponse>, I>>(base?: I): ArbsOnChainResponse {
    return ArbsOnChainResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArbsOnChainResponse>, I>>(object: I): ArbsOnChainResponse {
    const message = createBaseArbsOnChainResponse();
    message.chainId = object.chainId ?? 0;
    message.arbitrages = object.arbitrages?.map((e) => OnChainArbitrage.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
